# Generated by Django 4.1.2 on 2022-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=100)),
                ('moviename', models.CharField(max_length=100)),
                ('moviedirector', models.CharField(max_length=100)),
                ('releasedate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
